### ISSUE TITLE
Please use a more open license

### ISSUE THREAD

**Issue by acassis** [Broadcom-Network-Switching-Software/SDKLT#1]
Hi Broadcom,

Thank you very much for this great initiative.

However your Switch License and the Apache license will avoid it to be used on BSDs operating systems like NuttX, FreeBSD, OpenBSD, NetBSD, etc.

Apache license has "good intention", but it is written for lawyers not to developers and also when it try to avoid software patents it is in fact validating it. Many countries doesn't accept software patent, then the Apache license make things blur.

See the example of new Google Fuchsia, instead using Apache as they used on Android code, it is using a more freedom BSD license! Just my 2 cents! Please consider it!

**Comment by broadcom-ngsdk-mktg** [comment]
Hi, 
We did not understand your request clearly. Can you please send email directly to sdklt-feedback.pdl@broadcom.com?

Thank you,
Broadcom team
